<?php

/**
 * @var $field \Pars\Component\Components\Base\Fields\AbstractBlockquote
 * @var $bean \Niceshops\Bean\Type\Base\BeanInterface
 */
?>

<?php if ($field->hasLink()): ?>
<a href="<?= $field->getLink($bean) ?>" <?= $field->hasTarget() ? " target=\"{$field->getTarget()}\"" : '' ?>>
    <?php endif; ?>

    <blockquote class="blockquote<?= $field->hasAlign() ? ' text-' . $field->getAlign() : '' ?>">
        <p class="mb-0"><?= $field->getValue($bean) ?></p>
        <?php if ($field->hasFooter()): ?>
            <footer class="blockquote-footer"><?= $field->getFooter() ?>
                <?php if ($field->hasSource()): ?>
                    <cite title="<?= $field->getSource() ?>"><?= $field->getSource() ?></cite>
                <?php endif; ?>
            </footer>
        <?php endif; ?>
    </blockquote>

    <?php if ($field->hasLink()): ?>
</a>
<?php endif; ?>

