<?php

/**
 * @var $field \Pars\Component\Components\Base\Fields\AbstractButton
 * @var $bean \Niceshops\Bean\Type\Base\BeanInterface
 */
?>
<button
        type="<?= $field->getType() ?>"
        class="<?= $field->getClass() ?>"
        value="<?= $field->getValue($bean) ?>"
        name="<?= $field->getKey() ?>"
        id="<?= $field->getKey() ?>"
    <?= $field->isDisabled() ? ' disabled' : '' ?>>
    <?= $field->hasTitle() ? $field->getTitle() : '' ?>
</button>
