<?php

/**
 * @var $field \Pars\Component\Components\Base\Fields\AbstractCheckbox
 * @var $bean \Niceshops\Bean\Type\Base\BeanInterface
 * @var $errors array
 */
?>
<div class="form-group form-check">
    <input type="hidden" name="<?= $field->getKey() ?>" value="0">
    <input type="checkbox" class="form-check-input <?= is_array($errors) && count($errors) ? ' is-invalid ' : '' ?>"
           id="<?= $field->getKey() ?>"
           name="<?= $field->getKey() ?>"
           value="1"
        <?=$field->isRequired() ? ' required' : ''?>
        <?= $field->isChecked($bean) ? ' checked' : '' ?>>
    <?php if ($field->hasTitle()): ?>
        <label class="form-check-label" for="<?= $field->getKey() ?>"><?= $field->getTitle() ?></label>
    <?php endif;?>
    <?php if (is_array($errors)): ?>
        <?php foreach ($errors as $error): ?>
            <div id="<?= $field->getKey() ?>_Error" class="invalid-feedback">
                <?= $error ?>
            </div>
        <?php endforeach ?>
    <?php endif ?>
    <?php if ($field->hasHint()): ?>
        <small id="<?= $field->getKey() ?>__hint"
               class="form-text text-muted"><?= $field->getHint() ?></small>
    <?php endif; ?>
</div>
