<?php

/**
 * @var $field \Pars\Component\Components\Base\Fields\AbstractFigure
 * @var $bean \Niceshops\Bean\Type\Base\BeanInterface
 */
?>
<?php if ($field->hasLink()): ?>
<a href="<?= $field->getLink($bean) ?>" <?= $field->hasTarget() ? " target=\"{$field->getTarget()}\"" : '' ?>>
    <?php endif; ?>

    <figure class="figure">
        <?php if ($field->hasSource()): ?>
            <img src="<?= $field->getSource() ?>" class="figure-img img-fluid rounded"
                 alt="<?= $field->getValue($bean) ?>">
        <?php endif; ?>
        <figcaption
                class="figure-caption <?= $field->hasAlign() ? ' text-' . $field->getAlign() : '' ?>"><?= $field->getValue($bean) ?></figcaption>
    </figure>

    <?php if ($field->hasLink()): ?>
</a>
<?php endif; ?>
