<?php
/**
 * @var $field \Pars\Component\Components\Base\Fields\AbstractImage
 * @var $bean \Niceshops\Bean\Type\Base\BeanInterface
 */
?>
<?php if ($field->hasLink()): ?>
    <a href="<?= $field->getLink($bean) ?>" <?= $field->hasTarget() ? " target=\"{$field->getTarget()}\"" : '' ?>>
<?php endif; ?>
<?php if ($field->hasSource()): ?>
    <?php if ($field->hasAlign() && $field->getAlign() == \Pars\Component\Components\Base\Fields\AbstractText::ALIGN_CENTER): ?>
        <img
                src="<?= $field->getSource() ?>"
                class="<?= $field->hasSize() ? 'img-' . $field->getSize() : '' ?> mx-auto d-block"
                alt="<?= $field->getValue($bean) ?>">
    <?php else: ?>
        <img
                src="<?= $field->getSource() ?>"
                class="<?= $field->hasSize() ? 'img-' . $field->getSize() : '' ?>
               <?= $field->hasAlign() ? ' float-' . $field->getAlign() : '' ?>"
                alt="<?= $field->getValue($bean) ?>">
    <?php endif; ?>
<?php endif; ?>
<?php if ($field->hasLink()): ?>
    </a>
<?php endif; ?>
