<?php

/**
 * @var $field \Pars\Component\Components\Base\Fields\AbstractProgress
 * @var $bean \Niceshops\Bean\Type\Base\BeanInterface
 */
?>
<?php if ($field->hasLink()): ?>
<a href="<?= $field->getLink($bean) ?>" <?= $field->hasTarget() ? " target=\"{$field->getTarget()}\"" : '' ?>>
    <?php endif; ?>
    <div class="progress" <?= $field->hasHeight() ? "style=\"height: {$field->getHeight()}px;\"" : '' ?>>
        <div
                class="progress-bar progress-bar-striped <?= $field->hasStyle() ? 'bg-' . $field->getStyle() : '' ?>"
                role="progressbar"
                style="width: <?= $field->getValue($bean) ?>%"
                aria-valuenow="<?= $field->getValue($bean) ?>"
                aria-valuemin="0"
                aria-valuemax="100">
        </div>
    </div>
    <?php if ($field->hasLink()): ?>
</a>
<?php endif; ?>
