<?php
/**
 * @var $field \Pars\Component\Components\Base\Fields\AbstractRadioButtonGroup
 * @var $bean \Niceshops\Bean\Type\Base\BeanInterface
 */
?>
<?php foreach ($field->getSelectOptions() as $key => $value): ?>
    <div class="form-check">
        <input class="form-check-input <?= is_array($errors) && count($errors) ? ' is-invalid ' : '' ?>"
               type="radio"
               name="<?= $field->getKey() ?>"
               id="<?= $key ?>"
               value="<?= $key ?>"
            <?=$field->isRequired() ? ' required' : ''?>
            <?= $field->getValue($bean) == $key ? ' checked' : '' ?>>
        <label class="form-check-label" for="<?= $key ?>"><?= $value ?></label>
    </div>
<?php endforeach; ?>
<?php if (is_array($errors)): ?>
    <?php foreach ($errors as $error): ?>
        <div id="<?= $field->getKey() ?>_Error" class="invalid-feedback">
            <?= $error ?>
        </div>
    <?php endforeach ?>
<?php endif ?>
