<?php
/**
 * @var $field \Pars\Component\Components\Base\Fields\AbstractText
 * @var $bean \Niceshops\Bean\Type\Base\BeanInterface
 */
?>
<?php if ($field->hasLink()): ?>
    <a href="<?= $field->getLink($bean) ?>" <?= $field->hasTarget() ? " target=\"{$field->getTarget()}\"" : '' ?>>
<?php endif; ?>
    <div class="<?= $field->hasAlign() ? ' text-' . $field->getAlign() : '' ?>">
        <span class="<?= implode(' ', $field->getOption_List()) ?>"><?= $field->getValue($bean) ?></span>
    </div>
<?php if ($field->hasLink()): ?>
    </a>
<?php endif; ?>
