<?php
/**
 * @var $field \Pars\Component\Components\Base\Fields\AbstractTextarea
 * @var $bean \Niceshops\Bean\Type\Base\BeanInterface
 * @var $errors array
 */
?>
<div class="form-group">
    <?php if ($field->hasTitle()): ?>
        <label for="<?= $field->getKey() ?>"><?= $field->getTitle() ?></label>
    <?php endif; ?>
    <textarea class="form-control <?= is_array($errors) && count($errors) ? ' is-invalid ' : '' ?>"
              id="<?= $field->getKey() ?>"
              name="<?= $field->getKey() ?>"
        <?= $field->isRequired() ? ' required' : '' ?>
        <?= $field->hasRows() ? " rows=\"{$field->getRows()}\" " : '' ?>><?= $field->getValue($bean) ?></textarea>
    <?php if (is_array($errors)): ?>
        <?php foreach ($errors as $error): ?>
            <div id="<?= $field->getKey() ?>_Error" class="invalid-feedback">
                <?= $error ?>
            </div>
        <?php endforeach ?>
    <?php endif ?>
</div>
