<?php
/**
 * @var $component \Pars\Component\Components\Base\AbstractComponent
 * @var $templateFolder string
 */
?>
<?php foreach ($component->getBeanList() as $bean): ?>
    <div class="row row-cols-1 row-cols-sm-<?= $component->getCols() ?>">
        <?php foreach ($component->getFieldList() as $field): ?>
            <div class="col">
                <?php if ($field->isShow($bean)): ?>
                    <?php $this->insert($templateFolder . '::' . $field->getTemplate(), ['field' => $field, 'bean' => $bean]) ?>
                <?php endif; ?>
            </div>
        <?php endforeach ?>
    </div>
<?php endforeach ?>
