<?php
/**
 * @var $field \Pars\Component\Components\Edit\Fields\Text
 * @var $bean \Niceshops\Bean\Type\Base\BeanInterface
 * @var $errors array
 */
?>
<?php if ($field->getType() == \Pars\Component\Components\Edit\Fields\Text::TYPE_HIDDEN): ?>
    <input type="<?= $field->getType() ?>" id="<?= $field->getKey() ?>" name="<?= $field->getKey() ?>"
           value="<?= $field->getValue($bean) ?>">
<?php else: ?>
    <div class="form-group">
        <?php if ($field->hasTitle()): ?>
            <label for="<?= $field->getKey() ?>"><?= $field->getTitle() ?></label>
        <?php endif; ?>
        <input type="<?= $field->getType() ?>"
               class="form-control <?= count($errors) ? ' is-invalid' : '' ?>"
               id="<?= $field->getKey() ?>"
               name="<?= $field->getKey() ?>"
               value="<?= $field->getValue($bean) ?>"
            <?= $field->isRequired() ? ' required ' : '' ?>
            <?php if ($field->hasHint()): ?>
                aria-describedby="<?= $field->getKey() ?>__hint"
            <?php endif; ?>
            <?php if (count($errors)): ?>
                aria-describedby="<?= $field->getKey() ?>_Error"
            <?php endif; ?>
               autocomplete="<?= $field->getAutocomplete() ?>"
        >
        <?php foreach ($errors as $error): ?>
            <div id="<?= $field->getKey() ?>_Error" class="invalid-feedback">
                <?= $error ?>
            </div>
        <?php endforeach ?>
        <?php if ($field->hasHint()): ?>
            <small id="<?= $field->getKey() ?>__hint"
                   class="form-text text-muted"><?= $field->getHint() ?></small>
        <?php endif; ?>
    </div>
<?php endif; ?>
