<?php

/**
 * @var $component \Pars\Component\Components\Alert\Alert
 * @var $templateFolder string
 */
?>
<div class="alert alert-<?= $component->getStyle() ?>" role="alert">
    <?php if ($component->hasHeading()): ?>
        <h4 class="alert-heading"><?= $component->getHeading() ?></h4>
    <?php endif; ?>
    <?php foreach ($component->getBeanList() as $bean): ?>
        <?php foreach ($component->getFieldList() as $key => $field): ?>
            <?php if ($field->isShow($bean)): ?>
                <?= $field->hasTitle() ? "<h5>{$field->getTitle()}</h5>" : '' ?><?php $this->insert($templateFolder . '::' . $field->getTemplate(), ['field' => $field, 'bean' => $bean]) ?>
                <?= count($component->getFieldList()) > 1 && $key < count($component->getFieldList()) - 1 ? '<hr>' : '' ?>
            <?php endif; ?>
        <?php endforeach ?>
    <?php endforeach ?>
</div>
