<?php
/**
 * @var $component \Pars\Component\Components\Navigation\Navigation
 * @var $templateFolder string
 */
$componentList = $component->getComponentList();
?>
<ul class="nav nav-<?= $component->getType() ?> js-nav" id="<?= $component->getId() ?>" role="tablist">
    <?php foreach ($componentList as $key => $tabcomponent): ?>
        <li class="nav-item" role="presentation">
            <a class="nav-link<?= $key == $component->getActive() ? ' active' : '' ?>"
               id="<?= $tabcomponent->getId() ?>-tab"
               data-toggle="tab" href="#<?= $tabcomponent->getId() ?>" role="tab"
               aria-controls="<?= $tabcomponent->getId() ?>"
               aria-selected="<?= $key == $component->getActive() ? 'true' : 'false' ?>"
               data-index="<?= $key ?>">
                <?= $tabcomponent->hasTitle() ? $tabcomponent->getTitle() : '' ?>
            </a>
        </li>
    <?php endforeach; ?>
</ul>
<div class="tab-content" id="<?= $component->getId() ?>Content">
    <?php foreach ($componentList as $key => $tabcomponent): ?>
        <div class="tab-pane fade <?= $key == $component->getActive() ? ' show active' : '' ?>"
             id="<?= $tabcomponent->getId() ?>"
             role="tabpanel" aria-labelledby="<?= $tabcomponent->getId() ?>-tab">
            <?php $this->insert($templateFolder . '::' . $tabcomponent->getTemplate(), ['component' => $tabcomponent]) ?>
        </div>
    <?php endforeach; ?>
</div>

