<?php
/**
 * @var Pars\Component\View $view
 */

/**
 * @var string $templateFolder
 */
?>
<?php $this->layout($templateFolder . '::' . $view->getLayout()) ?>
<div class="row row-cols-<?= $view->getCols() ?>">
    <?php foreach ($view->getComponentList() as $component): ?>
        <div class="col">
            <?php if ($component->hasTitle()): ?>
                <h3><?= $component->getTitle() ?></h3>
            <hr>
            <?php endif; ?>
            <?php $this->insert($templateFolder . '::' . $component->getTemplate(), ['component' => $component]) ?>
        </div>
    <?php endforeach; ?>
</div>
<?php $this->push('javascript') ?>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js" integrity="sha256-H4Qt7pVBp547bdul9EtvPU/m+XQ9EQTsYH7zFe5W9Gw=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha256-XfzdiC+S1keia+s9l07y7ye5a874sBq67zK4u7LTjvk=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bs-custom-file-input@1.3.4/dist/bs-custom-file-input.min.js" integrity="sha256-e0DUqNhsFAzOlhrWXnMOQwRoqrCRlofpWgyhnrIIaPo=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/quill@1.3.7/dist/quill.min.js" integrity="sha256-xnX1c4jTWYY3xOD5/hVL1h37HCCGJx+USguyubBZsHQ=" crossorigin="anonymous"></script>
<script lang="js">
    $().ready(function ($) {
        $body = $('body');
        $body.off('click.handleNavState').on('click.handleNavState', '.js-nav', function (event) {
            $.get(window.location, {
                navid: $(event.currentTarget).attr('id'),
                navindex: $(event.target).data('index')
            });
        });
        feather.replace()
    });
</script>
<?php $this->stop() ?>
<?php $this->push('stylesheets') ?>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/quill@1.3.7/dist/quill.snow.css" integrity="sha256-jyIuRMWD+rz7LdpWfybO8U6DA65JCVkjgrt31FFsnAE=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/quill@1.3.7/dist/quill.bubble.css" integrity="sha256-2hxHujXw890GumwDHPWrwJCtdZZdrJanlGsrOTSfXnc=" crossorigin="anonymous">
<?php $this->stop() ?>

