<?php
/**
 * @var $component \Pars\Component\Components\Overview\Overview
 * @var $templateFolder string
 */

$fieldList = $component->getFieldList();
$count = count($fieldList);
?>
<div class="table-responsive">
    <table class="table table-striped table-hover table-bordered table-sm ">
        <thead class="bg-light">
        <tr>
            <?php $previousChapter = null ?>
            <?php $index = 1 ?>
            <?php foreach ($fieldList as $key => $field): ?>
                <?php if ($field->getChapter() == $previousChapter && $field->getChapter() != ''): ?>
                    <?= $field->hasTitle() ? $field->getTitle() : '' ?>
                <?php elseif ($previousChapter == null): ?>
                    <td>
                    <?= $field->hasTitle() ? $field->getTitle() : '' ?>
                <?php else: ?>
                    </td>
                    <td>
                    <?= $field->hasTitle() ? $field->getTitle() : '' ?>
                <?php endif; ?>
                <?php if ($index == $count): ?>
                    </td>
                <?php endif; ?>
                <?php $previousChapter = $field->getChapter() ?>
                <?php $index++; ?>
            <?php endforeach ?>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($component->getBeanList() as $bean): ?>
            <tr>
                <?php $previousChapter = null ?>
                <?php $index = 1 ?>
                <?php foreach ($fieldList as $field): ?>
                    <?php if ($field->getChapter() == $previousChapter && $field->getChapter() != ''): ?>
                        <?php if ($field->isShow($bean)): ?>
                            <?php $this->insert($templateFolder . '::' . $field->getTemplate(), ['field' => $field, 'bean' => $bean]) ?>
                        <?php endif; ?><?php elseif ($previousChapter == null): ?>
                        <td class="align-middle" <?= $field->hasWidth() ? 'style="width: ' . $field->getWidth() . 'px"' : '' ?>>
                        <?php if ($field->isShow($bean)): ?>
                            <?php $this->insert($templateFolder . '::' . $field->getTemplate(), ['field' => $field, 'bean' => $bean]) ?>
                        <?php endif; ?>
                    <?php else: ?>
                        </td>
                        <td class="align-middle" <?= $field->hasWidth() ? 'style="width: ' . $field->getWidth() . 'px"' : '' ?>>
                        <?php if ($field->isShow($bean)): ?>
                            <?php $this->insert($templateFolder . '::' . $field->getTemplate(), ['field' => $field, 'bean' => $bean]) ?>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($index == $count): ?>
                        </td>
                    <?php endif; ?>
                    <?php $previousChapter = $field->getChapter() ?>
                    <?php $index++; ?>
                <?php endforeach ?>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
